site_name: reddit-memes
repo_url: https://github.com/martimesteves1/reddit-memes
site_url: https://martimesteves1.github.io/reddit-memes
site_description: This project aims to predict meme success on Reddit with a multimodal approach using computer vision, generative AI and other techniques.
site_author: Francisco Gomes; Guilherme Raimundo; Marta Dinis; Martim Costa; Martim Esteves;
edit_uri: edit/main/docs/
repo_name: martimesteves1/reddit-memes
copyright: ""

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append('../')
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/martimesteves1/reddit-memes

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
